version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: colorlog
    versions:
    - 4.8.0
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: coverage
    versions:
    - "5.4"
    - "5.5"
  - dependency-name: mypy
    versions:
    - "0.800"
    - "0.812"
  - dependency-name: mysql-connector-python
    versions:
    - 8.0.23
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
  - dependency-name: requests
    versions:
    - 2.25.1
  - dependency-name: responses
    versions:
    - 0.12.1
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
  - dependency-name: slackclient
    versions:
    - 2.9.3
  - dependency-name: pytest-cov
    versions:
    - 2.10.1
